spring.application.name=airportManager
spring.datasource.url=jdbc:postgresql://localhost:5432/airportManager
spring.datasource.username=postgres
spring.datasource.password=amvaloaremare
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
